#!/bin/bash

echo "Checking $1"
exitcde=0

function bumpExitCode {
	if [[ $1 -gt $exitCode ]]; then
		set exitcode=$1
	fi
}

# BASH
if [[ `file $1 | grep "Bourne-Again shell script, ASCII text executable"` ]]; then
	echo "[INF] `pwd $1`: Bash script detected"
	# Validate
	if [[ `bash -n $1` ]]; then
		echo "[ERR] `pwd $1`: Invalid bash script detected"
	else
		echo "[INF] `pwd $1`: All ok!"
	fi
# PYTHON
elif [[ `file $1 | grep "Python script, ASCII text executable"` ]]; then
	echo "[INF] `pwd $1`: Python script detected"
    if [[ ! `python -m py_compile $1` ]]; then
		echo "[ERR] `pwd $1`: Invalid Python script detected"
		exit 2
	else
		echo "[INF] `pwd $1`: All ok!"
	fi
# YAML
elif [[ `file $1 | grep -i yaml` ]]; then
	echo "[INF] `pwd $1`: YAML file detected"
	# Validate
	if [[ ! `python -c 'import yaml,sys;yaml.safe_load(sys.stdin)' < $1` ]]; then
		echo "[INF] `pwd $1`: Seems to be valid YAML"
	else
		echo "[ERR] `pwd $1`: Invalid YAML detected"
		exit 2
	fi
else
	echo "[WRN] $1: Could not detect language. Please supply it manually with the --lang=LANGUAGE option. Exiting"
	bumpExitCode 1
fi

exit $exitCode
